# Generated by Django 5.2.6 on 2025-09-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='column',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.IntegerField(default=1),
        ),
    ]
